version: '3.1'

services:
  app:
    image: stolemyusername/flashcards:latest
    deploy:
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:fc.guythomas.me"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.port=8000"
        - "traefik.enable=true"
      placement:
        constraints:
         - node.role == manager
    networks:
      - traefik-net
    volumes:
      - flashcard-db:/src/db
volumes:
  flashcard-db:
networks:
  traefik-net:
    external: true