version: '3.1'

services:
  app:
    image: stolemyusername/flashcards:latest
    ports:
      -"8000:8000"
    networks:
      - traefik-net
    volumes:
      - flashcard-db:/src/db
volumes:
  flashcard-db:
networks:
  traefik-net:
    external: true